/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import controllers.ControllerVenda;
import model.Medicamento;
import model.Perfumaria;
import model.Produto;

import javax.swing.*;
import java.util.ArrayList;

/**
 *
 * @author 202112030001
 */
public class JanelaVenda extends javax.swing.JInternalFrame {
private ControllerVenda controllerVenda;
    /**
     * Creates new form JanelaVenda
     */
    public JanelaVenda() {
        controllerVenda = new ControllerVenda();
        initComponents();
        listarMedicamentos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jPanel2 = new javax.swing.JPanel();
        lblNomeCliente = new javax.swing.JLabel();
        txtNomeCliente = new javax.swing.JTextField();
        lblTeladeVendas = new javax.swing.JLabel();
        lblMendicamentosTitulo = new javax.swing.JLabel();
        lblQTDMedicamentos = new javax.swing.JLabel();
        txtQntMed1 = new javax.swing.JTextField();
        lblPerfumes = new javax.swing.JLabel();
        lblQTDPerfume = new javax.swing.JLabel();
        txtQTDPerfume = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListPerfume = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListMedicamentos = new javax.swing.JList<>();
        txtPerfumes = new javax.swing.JTextField();
        lblMedicamentos = new javax.swing.JLabel();
        txtMedicamentos = new javax.swing.JTextField();
        lblPerfume = new javax.swing.JLabel();
        btnCadVenda = new javax.swing.JButton();
        lblMedicamentosItem = new javax.swing.JLabel();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Venda");

        lblNomeCliente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblNomeCliente.setText("Nome do cliente:");

        lblTeladeVendas.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblTeladeVendas.setText("Tela de Vendas");

        lblMendicamentosTitulo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblMendicamentosTitulo.setText("Medicamentos");

        lblQTDMedicamentos.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblQTDMedicamentos.setText("Quantidade Medicamentos:");

        lblPerfumes.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblPerfumes.setText("Perfumes:");

        lblQTDPerfume.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblQTDPerfume.setText("Quatidade Perfumes:");

        jScrollPane1.setViewportView(jListPerfume);

        jListMedicamentos.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jListMedicamentosComponentHidden(evt);
            }
        });


        jScrollPane2.setViewportView(jListMedicamentos);

        txtPerfumes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPerfumesActionPerformed(evt);
            }
        });

        lblMedicamentos.setText("Medicamentos:");

        lblPerfume.setText("Perfume");

        btnCadVenda.setText("Cadastrar Venda");

        lblMedicamentosItem.setText("Medicamentos");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblMendicamentosTitulo)
                            .addComponent(lblTeladeVendas)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblNomeCliente)
                                            .addComponent(lblPerfumes))
                                        .addGap(18, 18, 18))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(lblMedicamentos)
                                        .addGap(29, 29, 29)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMedicamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPerfumes, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(lblQTDMedicamentos)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtQntMed1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(lblQTDPerfume)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtQTDPerfume, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPerfume)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMedicamentosItem)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(btnCadVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTeladeVendas)
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMendicamentosTitulo)
                    .addComponent(lblPerfume)
                    .addComponent(lblMedicamentosItem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNomeCliente))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPerfumes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPerfumes))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMedicamentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMedicamentos))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtQTDPerfume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblQTDPerfume))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblQTDMedicamentos)
                            .addComponent(txtQntMed1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(41, 41, 41)
                .addComponent(btnCadVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(206, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public  void listarMedicamentos(){
        ListModel<Produto> model = (ListModel<Produto>)  jListMedicamentos.getModel();
        int tamanho = model.getSize();
        for( int i = 0;i<tamanho;i++){
            jListMedicamentos.remove(0);
        }
        ArrayList<Produto> produtos = controllerVenda.listMedicamentos();
        DefaultListModel<Produto> listModel = new DefaultListModel<>();

        for (Produto produto: produtos) {
            listModel.addElement(produto);
        }
        jListMedicamentos.setModel(listModel);
    }
    private void txtPerfumesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPerfumesActionPerformed



    }//GEN-LAST:event_txtPerfumesActionPerformed

    private void jListMedicamentosComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jListMedicamentosComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_jListMedicamentosComponentHidden


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadVenda;
    private javax.swing.JList<Produto> jListMedicamentos;
    private javax.swing.JList<Produto> jListPerfume;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblMedicamentos;
    private javax.swing.JLabel lblMedicamentosItem;
    private javax.swing.JLabel lblMendicamentosTitulo;
    private javax.swing.JLabel lblNomeCliente;
    private javax.swing.JLabel lblPerfume;
    private javax.swing.JLabel lblPerfumes;
    private javax.swing.JLabel lblQTDMedicamentos;
    private javax.swing.JLabel lblQTDPerfume;
    private javax.swing.JLabel lblTeladeVendas;
    private javax.swing.JTextField txtMedicamentos;
    private javax.swing.JTextField txtNomeCliente;
    private javax.swing.JTextField txtPerfumes;
    private javax.swing.JTextField txtQTDPerfume;
    private javax.swing.JTextField txtQntMed1;
    // End of variables declaration//GEN-END:variables
}
