/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import controllers.ControllerVenda;
import model.Medicamento;
import model.Perfumaria;
import model.Produto;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;

/**
 *
 * @author 202112030001
 */
public class JanelaVenda extends javax.swing.JInternalFrame {
private ControllerVenda controllerVenda;
    /**
     * Creates new form JanelaVenda
     */
    public JanelaVenda() {
        controllerVenda = new ControllerVenda();
        initComponents();
        listarMedicamentos();
        listarPerfumaria();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jPanel2 = new javax.swing.JPanel();
        lblNomeCliente = new javax.swing.JLabel();
        txtNomeCliente = new javax.swing.JTextField();
        lblTeladeVendas = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListPerfume = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListMedicamentos = new javax.swing.JList<>();
        lblPerfume = new javax.swing.JLabel();
        btnCadVenda = new javax.swing.JButton();
        lblMedicamentosItem = new javax.swing.JLabel();
        btnInserirPerfume = new javax.swing.JButton();
        btnInserirMed = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblProdutos = new javax.swing.JTable();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Venda");

        lblNomeCliente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblNomeCliente.setText("Nome do cliente:");

        lblTeladeVendas.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblTeladeVendas.setText("Tela de Vendas");

        jListPerfume.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListPerfumeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jListPerfume);

        jListMedicamentos.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jListMedicamentosComponentHidden(evt);
            }
        });
        jScrollPane2.setViewportView(jListMedicamentos);

        lblPerfume.setText("Perfume");

        btnCadVenda.setText("Cadastrar Venda");
        btnCadVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadVendaActionPerformed(evt);
            }
        });

        lblMedicamentosItem.setText("Medicamentos");

        btnInserirPerfume.setText("Inserir Perfume");
        btnInserirPerfume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirPerfumeActionPerformed(evt);
            }
        });

        btnInserirMed.setText("Inserir Medicamento");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(lblTeladeVendas)
                        .addGap(0, 14, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblNomeCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPerfume)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMedicamentosItem)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnInserirPerfume)
                .addGap(181, 181, 181)
                .addComponent(btnInserirMed)
                .addGap(104, 104, 104))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(301, 301, 301)
                .addComponent(btnCadVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTeladeVendas)
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPerfume)
                    .addComponent(lblMedicamentosItem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNomeCliente)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnInserirPerfume)
                    .addComponent(btnInserirMed))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(btnCadVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tblProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tblProdutos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public  void listarMedicamentos(){
        ListModel<Produto> model = (ListModel<Produto>)  jListMedicamentos.getModel();
        int tamanho = model.getSize();
        for( int i = 0;i<tamanho;i++){
            jListMedicamentos.remove(0);
        }
        ArrayList<Produto> produtos = controllerVenda.listMedicamentos();
        DefaultListModel<Produto> listModel = new DefaultListModel<>();

        for (Produto produto: produtos) {
            listModel.addElement(produto);
            System.out.println("teste");
        }
        jListMedicamentos.setModel(listModel);
    }
    private static java.sql.Date obterdata(){
        LocalDate  dataAtual= LocalDate.now();

        return java.sql.Date.valueOf(dataAtual);

    }
    public  void listarPerfumaria(){
        ListModel<Produto> model = (ListModel<Produto>)  jListPerfume.getModel();
        int tamanho = model.getSize();
        for( int i = 0;i<tamanho;i++){
            jListPerfume.remove(0);
        }
        ArrayList<Produto> produtos = controllerVenda.listPerfumaria();
        DefaultListModel<Produto> listModel = new DefaultListModel<>();

         for(Produto produto: produtos) {

            listModel.addElement(produto);
        }
        jListPerfume.setModel(listModel);
    }
    private void jListMedicamentosComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jListMedicamentosComponentHidden

        // TODO add your handling code here:
    }//GEN-LAST:event_jListMedicamentosComponentHidden

    private void btnCadVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadVendaActionPerformed
    String nome_cliente = txtNomeCliente.getText().trim();


        

    }//GEN-LAST:event_btnCadVendaActionPerformed

    private void btnInserirPerfumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirPerfumeActionPerformed
    int[] indices = jListMedicamentos.getSelectedIndices();
    for(int i =0;i<indices.length;i++){
       String nome= jListPerfume.getSelectedValue().getNome_comercial();
        jListPerfume.getSelectedValue().getQuantidade();
        jListPerfume.getSelectedValue().getNumero();
        System.out.println(nome);
    }

    }//GEN-LAST:event_btnInserirPerfumeActionPerformed

    private void jListPerfumeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListPerfumeMouseClicked
       

    }//GEN-LAST:event_jListPerfumeMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadVenda;
    private javax.swing.JButton btnInserirMed;
    private javax.swing.JButton btnInserirPerfume;
    private javax.swing.JList<Produto> jListMedicamentos;
    private javax.swing.JList<Produto> jListPerfume;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblMedicamentosItem;
    private javax.swing.JLabel lblNomeCliente;
    private javax.swing.JLabel lblPerfume;
    private javax.swing.JLabel lblTeladeVendas;
    private javax.swing.JTable tblProdutos;
    private javax.swing.JTextField txtNomeCliente;
    // End of variables declaration//GEN-END:variables
}
